name: bckr

services:
  hugo:
    image: hugomods/hugo:go-git-0.163.1@sha256:d8f57e4dff49f41fa7e0a605eeb59f08374bd4e2075d0f8da6b7b0aba52a76ef
    command: server -D
    volumes:
      - .:/src
      # - hugo_cache:/tmp/hugo_cache
    working_dir: /src/site
    ports:
      - 1313:1313
    user: 1000:1000

volumes:
  hugo_cache:
