name: bckr

services:
  hugo:
    image: hugomods/hugo:go-git-0.145.0
    command: server -D
    volumes:
      - .:/src
      - hugo_cache:/tmp/hugo_cache
    working_dir: /src/site
    ports:
      - 1313:1313

volumes:
  hugo_cache:
