# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL: 'https://bckr.me/'
defaultContentLanguage: en
enableRobotsTXT: true
pagination:
  pagerSize: 10
  summaryLength: 0
  enableGitInfo: true
frontmatter:
  lastmod:
    - lastmod
    - ':default'
outputs:
  home:
    - HTML
    - RSS
    - JSON
module:
  proxy: direct
  hugoVersion:
    extended: true
    min: 0.136.2
  imports:
    - path: github.com/jpanther/congo/v2
      disable: false
    - path: github.com/hugomods/icons/vendors/bootstrap
    - path: github.com/hugomods/icons/vendors/font-awesome
