name: Build dev

on:
  push:
    branches-ignore:
      - master
      - main
  pull_request:
    types: [opened, reopened]
    branches:
      - 'main'

jobs:
  spellcheck:
    uses: austenstone/spellchecker-cli-action-summary/.github/workflows/spellcheck.yml@main

  build:
    runs-on:         ubuntu-latest
    name:            Build branch
    steps:
      - name:        Checkout
        uses:        actions/checkout@v1

      - name:        Run the build action
        id:          build
        uses:        blbecker/hugo-build@v0.111.3-1
        with:
          hugo_args: -D
