name: Build dev

on:
  pull_request:
    branches:
      - 'main'

jobs:
  spellcheck:
    uses: austenstone/spellchecker-cli-action-summary/.github/workflows/spellcheck.yml@main

  build:
    runs-on:         ubuntu-latest
    name:            Build branch
    steps:
      - name:        Checkout
        uses:        actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3
        with:
          hugo-version: '0.120.3'
          # extended: true

      - name: Build
        run: hugo --minify -D
