name: Build dev

on:
  push:
    branches-ignore:
      - master
      - main
  pull_request:
    types: [opened, reopened]
    branches:
      - 'main'

jobs:
  spellcheck:
    uses: austenstone/spellchecker-cli-action-summary/.github/workflows/spellcheck.yml@main

  build:
    runs-on:         ubuntu-latest
    name:            Build branch
    steps:
      - name:        Checkout
        uses:        actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.120.3'
          # extended: true

      - name: Build
        run: hugo --minify -D
