on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on:              ubuntu-latest
    name:                 Build branch
    steps:
      - name:              Checkout
        uses:              actions/checkout@v1

      - name:               Run the build action
        id:                 build
        uses:               blbecker/hugo-build@master
        with:
          hugo_args: -D