name: Validate PR

on:
  pull_request:
    branches:
      - 'main'

jobs:
  spellcheck:
    uses: austenstone/spellchecker-cli-action-summary/.github/workflows/spellcheck.yml@main

  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on:         ubuntu-latest
    name:            Hugo Build
    steps:
      - name:        Checkout
        uses:        actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3
        with:
          hugo-version: '0.136.2'
          extended: true

      - name: Build
        run: hugo -D --environment=development
        working-directory: ./site

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hugo-build
          path: |
            site/public
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: [build,gitleaks,spellcheck]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: hugo-build
          path: public

      - name: Deploy
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public --project-name=bckr-me --branch ${{ github.head_ref }}

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          comment-tag: deployment
          message: |
            PR deployed to ${{ steps.deploy.outputs.deployment-alias-url }} ! :rocket: