name: Build and Deploy to live site

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on:              ubuntu-latest
    name:                 Build and deploy master
    steps:
      - name:        Checkout
        uses:        actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3
        with:
          hugo-version: '0.120.3'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hugo-build
          path: |
            public

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: hugo-build
          path: public

      - name: Deploy
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public --project-name=bckr-me --branch ${{ github.ref_name }}