name: Build and Deploy to live site

on:
  push:
    branches:
      - master
      - main

jobs:
  build_and_deploy:
    runs-on:              ubuntu-latest
    name:                 Build and deploy master
    steps:
    -  name:              Checkout
       uses:              actions/checkout@v1

    - name:               Run the build action
      id:                 build
      uses:               blbecker/hugo-build@v0.111.3-1

    - name:               Run the deploy action
      id:                 deploy
      uses:               blbecker/rsync-deploy@1.1
      with:
        destination_host: ${{ secrets.DeploymentHost }}
        destination_path: ~/bckr.me/
        deployment_key:   ${{ secrets.DeploymentKey }}
        deployment_user:  ${{ secrets.DeploymentUser }}
        source_dir:       public/
