on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on:              ubuntu-latest
    name:                 Build and deploy master
    steps:
    -  name:              Checkout
       uses:              actions/checkout@v1

    - name:               Run the build and deploy action
      id:                 build_and_deploy
      uses:               blbecker/hugo-build-rsync-action@master
      with:
        destination_host: ${{ secrets.DeploymentHost }}
        destination_path: ~/bckr.me/
        deployment_key:   ${{ secrets.DeploymentKey }}
        deployment_user:  ${{ secrets.DeploymentUser }}

# No op 8
