name: Build and Deploy to live site

on:
  push:
    branches:
      - master
      - main

jobs:
  build_and_deploy:
    runs-on:              ubuntu-latest
    name:                 Build and deploy master
    steps:
      - name:        Checkout
        uses:        actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@16361eb4acea8698b220b76c0d4e84e1fd22c61d # v2
        with:
          hugo-version: '0.120.3'
          # extended: true

      - name: Build
        run: hugo --minify

      - name:               Run the deploy action
        id:                 deploy
        uses:               blbecker/rsync-deploy@1.1
        with:
          destination_host: ${{ secrets.DeploymentHost }}
          destination_path: ~/bckr.me/
          deployment_key:   ${{ secrets.DeploymentKey }}
          deployment_user:  ${{ secrets.DeploymentUser }}
          source_dir:       public/
