on:                       [push]

jobs:
  build_and_deploy:
    runs-on:              ubuntu-latest
    name:                 Build and deploy master
    steps:
    -  name:              Checkout
       uses:              actions/checkout@v1

    - name:               Run the build and deploy action
      id:                 build_and_deploy
      uses:               blbecker/hugo-build-rsync-action@master
      with:
        destination-host: example.com
        destination-path: remote/path
      env:                # Or as an environment variable
        super_secret:     ${{ secrets.DEPLOY_PRIVATE_KEY }}

# No op
